#!/bin/bash

echo "blogPushToProduction"
if [ -f /home/wzjzus5/wzjz.us/Apps/blogcommon ]
then
    . /home/wzjzus5/wzjz.us/Apps/blogcommon
fi

if [ "$USER" != "wzjzus5" ]
then
    echo "Run 'su wzjzus5' first!"
    echo "and run 'exit' after"
    exit 1
fi

PushToProdFolder="/home/wzjzus5/wzjz.us/PushToProduction"
# zipFileRootName MUST match zipFileRootName in /home/Walt/Documents/Apps/mcgAppPushToProduction
zipFileRootName="blog_Prod_"

DeleteOldReleases() {
    echo "Deleting old releases"
	daysToKeep=10
	numberToKeep=10
#	find "${folder}" -name "${folderSpec}" -type d -ctime +${daysToKeep} -exec rm -rf {} \;
	
	secondsSinceEpoch=$(date -d "${daysToKeep} days ago" "+%s")
	stat -c "%Y %n" ${PushToProdFolder}/${zipFileRootName}*.zip | sort -nr | tail -n +${numberToKeep} | while read -r mtime name; do
        if (( mtime < secondsSinceEpoch )); then
            echo "remove $name"
            rm "$name"
        fi
	done
}

# Get the latest zip file.  All releases are full releases so that's all we should ever need to process.
cd "${PushToProdFolder}"
fileName=$(ls --sort=time blog_Prod_* | head --lines=1)
echo "About to push ${fileName} to Production"
pause

cd "${ProdFolder}"
if [ "${ProdFolder}" != "$PWD" ]
then
    echo "Not in Prod folder"
    echo "ProdFolder='${ProdFolder}'"
    echo "pwd='$PWD'"
    exit 3
fi
echo "Unzipping ${PushToProdFolder}/${fileName}"
unzip -q -o "${PushToProdFolder}/${fileName}"
if [ "$?" != "0" ]
then
    echo "Unzip failed"
    echo "App is still down"
    exit 4
fi

python -m ensurepip --upgrade
pip install Flask
pip install python-dotenv
pip install Markdown

DeleteOldReleases

echo "blogPushToProduction Done!"
echo "Now, exit from wzjzus5 and run blogCopyApps"
