#!/bin/bash

if [ -f /home/wzjzus5/public_html/Blog/Apps/blogcommon ]
then
    . /home/wzjzus5/public_html/Blog/Apps/blogcommon
fi

echo "Copying Blog apps"
chmod +x /home/wzjzus5/public_html/Blog/Apps/*
cp /home/wzjzus5/public_html/Blog/Apps/* /usr/local/bin

echo "Setting Blog file permissions"
# ProdFolder is defined in blogcommon
chown --recursive wzjzus5 "${ProdFolder}"
chmod --recursive 0755 "${ProdFolder}"

echo "blogCopyApps Done."
