#!/bin/bash

if [ "$USER" != "root" ]
then
    echo "Not running as root!"
    exit 1
fi

if [ -f /home/wzjzus5/public_html/Apps/blogcommon ]
then
    . /home/wzjzus5/public_html/Apps/blogcommon
fi

echo "Copying Blog apps"
chmod +x ${ProdFolder}/Apps/*
cp ${ProdFolder}/Apps/* /usr/local/bin

echo "Setting Blog file permissions"
# ProdFolder is defined in blogcommon
chown --recursive wzjzus5 "${ProdFolder}"
chmod --recursive 0755 "${ProdFolder}"

echo "blogCopyApps Done."
